### PR TITLE
Support Actix 3.*

### LINKED ISSUE #39: Support Actix 3.3
Support the latest versions of Actix and also support the following syntax which is introduced in Actix 3.0

```
async fn index(QsQuery(my_param): QsQuery<MyStruct>) {
}
```

### PR DESCRIPTION
**Pull request by omid**
In this PR, I've upgraded the version of Actix to 3+.

As bonus:
- Upgrade serde_urlencoded dep to 0.7.
- Add a new CHANGES.md file to be able to track changes in different versions.
- Some tiny code style issues, thanks to `cargo fmt`

fix #39

### CODE REVIEW

**Comment by omid** [comment]
Hey @samscott89, how can I push it forward?

**Comment by samscott89** [comment]
Thank @omid. Will review tonight!

**Comment by samscott89** [comment]
Hey @omid . Thanks for opening this and the contributions!

I did some of the housekeeping matters - updating dependencies and running cargo fmt.
And added actix support in v0.8. v2 is supported via `actix2` if anyone needs.

I'm not a huge fan of making the inner type `pub` so people can access it that way, since then we are committing to not changing the internal structure. The example you gave doesn't suggest any benefits when used with `Deref`. There is also the `into_inner` method if you need to recover the inner type.

**Comment by omid** [comment]
Yes, but that's how actix works, https://github.com/actix/actix-web/blob/master/src/types/query.rs#L54
The ticket for Query: https://github.com/actix/actix-web/issues/987

**Pull request closed without merging**
