### PR TITLE
actix-web v2 and other dep updates

### PR DESCRIPTION
**Pull request by Tarnadas**
This PR updates actix-web to v2.
I also updated all other dependencies, updated to Rust edition 2018 and removed no longer supported rustfmt options.

### CODE REVIEW

**Comment by Tarnadas** [comment]
@samscott89 now that all actix tests are green and have been added to the CI pipeline, this PR is ready for review

**Comment by Tarnadas** [comment]
@samscott89 bump

**Comment by samscott89** [comment]
Hey @Tarnadas, many thanks for doing this and apologies for the complete silence. Been fully distracted with other work. I'll rebase these changes locally and get them merged now.

**Comment by samscott89** [comment]
Thank you again for doing this, just merged in the rebased version #30. Will publish as 0.6 soon.

**Pull request closed without merging**
