### PR TITLE
Actix 4

### PR DESCRIPTION
**Pull request by omid**

### CODE REVIEW

**Comment by SecretKeeper** [comment]
any updates related to merge this?

**Comment by SecretKeeper** [comment]
any updates related to merge this?

**Comment by samscott89** [comment]
Oh nice, thanks for the contribution @omid ! This looks good to me.

One bikeshedding problem -- this would be a breaking change since the `actix` feature will move from importing version 3 to version 4. Wondering whether to number all the features (`actix2, actix3, actix4`) instead? It will also be breaking, but ideally in a slightly more helpful way.

**Comment by omid** [comment]
yep, I'm fine with that.
I actually wanted to do so... but also define `actix` feature to just enable `actix4` in it.
But you are right, better to have it per actix version.

**Comment by omid** [comment]
found some issues! but anyway, now I'm done :P

**Comment by samscott89** [comment]
Amazing, thank you @omid !

**Pull request merged**
